services:
  migsfy-bot:
    build: .
    container_name: migsfy-bot
    restart: unless-stopped

    # Environment variables from .env file
    env_file:
      - .env

    # Additional environment variables for user permissions
    environment:
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}

    # Volumes for data persistence - mount only data directories
    volumes:
      - /DATA/AppData/migsfy:/app/data
      - /media/devmon/SOLAR/media:/media
      - ./.env:/app/.env:ro

    # Network configuration
    networks:
      - migsfy-network

    # Keep container running
    command: ["--daemon"]

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  migsfy-network:
    driver: bridge

volumes:
  migsfy-data:
  migsfy-cache:
